### ISSUE TITLE
敏感操作tips

### ISSUE THREAD

**Issue by evilAdan0s** [EvilAnne/Violation_Pnetest#1]
- 在进行有可能导致管理员察觉的敏感操作时（如登录远程桌面等），根据目标所在地区，选择目标处于深夜时进行

**Comment by EvilAnne** [comment]
感谢，已更新！
登录服务器如果是某地区，或者某国，最好还是用当地的，不然确实会有提示。
之前遇到服务器，只有当地区域的IP才能访问到3389，防火墙做过一些策略。
